# Specify the version for docker-compose.yml
version: '3.1'

# add the services needed (postgres,go)
services:
  users:
    container_name: users
    # build the Dockerfile, alternatively use an image.
    build:
      context: ./../
      dockerfile: ./deployments/Dockerfile
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: romax
      POSTGRES_PASSWORD: mypassword
      # Optional: Give a name to the database, otherwise
      # use the default value POSTGRES_USER as a database name (user in this case.)
      # POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - ./deployments/postgres/init/init_table.sql:/docker-entrypoint-initdb.d/init.sql
#      - ./deployments/postgres/data:/var/lib/postgresql/data
