# Specify the version for docker-compose.yml
version: '3.1'

# add the services needed (postgres,go)
services:
  users:
    container_name: users
    # build the Dockerfile, alternatively use an image.
    build:
      context: ./../
      dockerfile: ./deployments/Dockerfile
    depends_on:
      - postgres
    ports:
      - "8084:8084"
    networks:
      - default

  postgres:
    container_name: postgresCont
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: romax
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: romax
    ports:
      - "5432:5432"
