# Specify the version for docker-compose.yml
version: '3.1'

# add the services needed (postgres,go)
services:
  users:
    container_name: users
    command: ["./wait-for-it.sh", "postgres", "go", "main.go"]
    # build the Dockerfile, alternatively use an image.
    build:
      context: ./../
      dockerfile: ./deployments/Dockerfile
    depends_on:
      - postgres
    ports:
      - "8084:8084"
    environment:
      DB_PASSWORD: mypassword
    volumes:
      - .:/go/src/github.com/pavel/gorm-psql
    links:
      - postgres

  postgres:
    container_name: postgres-db
    image: postgres:latest
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U romax" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: romax
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: romax
    ports:
      - "5432:5432"