# Specify the version for docker-compose.yml
version: "3.4"

# add the services needed (postgres,go)
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mypassword
      # Optional: Give a name to the database, otherwise
      # use the default value POSTGRES_USER as a database name (user in this case.)
      # POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  go:
    container_name: users
    # build the Dockerfile, alternatively use an image.
    build:
      context: .
    depends_on:
      - "postgres"

volumes:
  dbdata: # create the volume for persisting data.